services:
  service:
    build: .
    ports:
      - 8000:5000
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: cloutbot
      MONGO_INITDB_ROOT_PASSWORD: sw4g_cloutbot
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: cloutbot
      ME_CONFIG_MONGODB_ADMINPASSWORD: sw4g_cloutbot
      ME_CONFIG_MONGODB_URL: mongodb://cloutbot:sw4g_cloutbot@mongo:27017/
      ME_CONFIG_BASICAUTH: false